- name: Updates
  hosts: all
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: true

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: true

  - name: Upgrade packages
    apt: 
      upgrade: dist
    become: true

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
    become: true

  - name: Check if a reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    when: reboot_required_file.stat.exists
    become: true

  - name: Waiting for server to come back
    local_action: 
      module: wait_for
        port=22
        host={{ inventory_hostname }}
        search_regex=OpenSSH
        delay=10
    become: false
